# Generated by Django 2.0.2 on 2018-02-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('taxa', models.FloatField(blank=True, default=None, null=True)),
                ('instituicao_finaceira', models.CharField(max_length=30)),
                ('valor_investido', models.FloatField(blank=True, default=None, null=True)),
                ('corretora', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('vencimento', models.DateField()),
                ('valor_atual', models.FloatField(blank=True, default=None, null=True)),
                ('valor_liquido', models.FloatField(blank=True, default=None, null=True)),
                ('imposto', models.FloatField(blank=True, default=None, null=True)),
                ('projecao', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
